# Generated by Django 4.2.9 on 2026-01-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="dingtalk_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="钉钉ID",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="feishu_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="飞书ID",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="wechat_work_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="企业微信ID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dingtalk_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="钉钉ID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="feishu_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="飞书ID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="wechat_work_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="企业微信ID",
            ),
        ),
    ]
