# Generated by Django 4.2.9 on 2026-01-30 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="数据源名称")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mysql", "MySQL"),
                            ("postgresql", "PostgreSQL"),
                            ("clickhouse", "ClickHouse"),
                            ("elasticsearch", "Elasticsearch"),
                            ("mongodb", "MongoDB"),
                        ],
                        max_length=20,
                        verbose_name="数据源类型",
                    ),
                ),
                ("host", models.CharField(max_length=255, verbose_name="主机地址")),
                ("port", models.IntegerField(verbose_name="端口")),
                (
                    "database_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="数据库名"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="用户名"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="加密存储",
                        max_length=255,
                        null=True,
                        verbose_name="密码",
                    ),
                ),
                (
                    "extra_config",
                    models.JSONField(blank=True, default=dict, verbose_name="额外配置"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "正常"), ("inactive", "停用"), ("error", "异常")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "last_check_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后检查时间"),
                ),
                (
                    "last_check_result",
                    models.TextField(blank=True, null=True, verbose_name="最后检查结果"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据源",
                "verbose_name_plural": "数据源",
                "db_table": "t_datasource",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="报表名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "query_config",
                    models.JSONField(help_text="SQL查询配置", verbose_name="查询配置"),
                ),
                (
                    "display_type",
                    models.CharField(
                        choices=[
                            ("table", "表格"),
                            ("line", "折线图"),
                            ("bar", "柱状图"),
                            ("pie", "饼图"),
                            ("funnel", "漏斗图"),
                            ("gauge", "仪表盘"),
                            ("heatmap", "热力图"),
                            ("card", "卡片指标"),
                            ("progress", "进度条"),
                        ],
                        default="table",
                        max_length=20,
                        verbose_name="展示类型",
                    ),
                ),
                (
                    "display_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="图表类型、列配置等",
                        verbose_name="展示配置",
                    ),
                ),
                (
                    "filter_config",
                    models.JSONField(blank=True, default=list, verbose_name="筛选条件配置"),
                ),
                (
                    "format_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="金额千分位、百分比等",
                        verbose_name="格式化配置",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公开")),
                ("view_count", models.IntegerField(default=0, verbose_name="查看次数")),
                (
                    "enable_watermark",
                    models.BooleanField(default=False, verbose_name="启用水印"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "datasource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="report.datasource",
                        verbose_name="数据源",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "报表",
                "verbose_name_plural": "报表",
                "db_table": "t_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalReport",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="更新时间"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="报表名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "query_config",
                    models.JSONField(help_text="SQL查询配置", verbose_name="查询配置"),
                ),
                (
                    "display_type",
                    models.CharField(
                        choices=[
                            ("table", "表格"),
                            ("line", "折线图"),
                            ("bar", "柱状图"),
                            ("pie", "饼图"),
                            ("funnel", "漏斗图"),
                            ("gauge", "仪表盘"),
                            ("heatmap", "热力图"),
                            ("card", "卡片指标"),
                            ("progress", "进度条"),
                        ],
                        default="table",
                        max_length=20,
                        verbose_name="展示类型",
                    ),
                ),
                (
                    "display_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="图表类型、列配置等",
                        verbose_name="展示配置",
                    ),
                ),
                (
                    "filter_config",
                    models.JSONField(blank=True, default=list, verbose_name="筛选条件配置"),
                ),
                (
                    "format_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="金额千分位、百分比等",
                        verbose_name="格式化配置",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公开")),
                ("view_count", models.IntegerField(default=0, verbose_name="查看次数")),
                (
                    "enable_watermark",
                    models.BooleanField(default=False, verbose_name="启用水印"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "datasource",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="report.datasource",
                        verbose_name="数据源",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 报表",
                "verbose_name_plural": "historical 报表",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDataSource",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="更新时间"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="数据源名称")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mysql", "MySQL"),
                            ("postgresql", "PostgreSQL"),
                            ("clickhouse", "ClickHouse"),
                            ("elasticsearch", "Elasticsearch"),
                            ("mongodb", "MongoDB"),
                        ],
                        max_length=20,
                        verbose_name="数据源类型",
                    ),
                ),
                ("host", models.CharField(max_length=255, verbose_name="主机地址")),
                ("port", models.IntegerField(verbose_name="端口")),
                (
                    "database_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="数据库名"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="用户名"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="加密存储",
                        max_length=255,
                        null=True,
                        verbose_name="密码",
                    ),
                ),
                (
                    "extra_config",
                    models.JSONField(blank=True, default=dict, verbose_name="额外配置"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "正常"), ("inactive", "停用"), ("error", "异常")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "last_check_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后检查时间"),
                ),
                (
                    "last_check_result",
                    models.TextField(blank=True, null=True, verbose_name="最后检查结果"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 数据源",
                "verbose_name_plural": "historical 数据源",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ReportSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[("daily", "每日"), ("weekly", "每周"), ("monthly", "每月")],
                        max_length=20,
                        verbose_name="推送周期",
                    ),
                ),
                (
                    "schedule_config",
                    models.JSONField(
                        default=dict, help_text="具体推送时间配置", verbose_name="具体时间配置"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "邮件"),
                            ("dingtalk", "钉钉"),
                            ("feishu", "飞书"),
                            ("wechat", "企业微信"),
                        ],
                        max_length=20,
                        verbose_name="推送渠道",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("pdf", "PDF"),
                            ("image", "图片"),
                        ],
                        default="excel",
                        max_length=20,
                        verbose_name="导出格式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("paused", "暂停")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "last_sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后推送时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="report.report",
                        verbose_name="报表",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="订阅用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "报表订阅",
                "verbose_name_plural": "报表订阅",
                "db_table": "t_report_subscription",
                "unique_together": {("report", "user")},
            },
        ),
        migrations.CreateModel(
            name="ReportFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="report.report",
                        verbose_name="报表",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "报表收藏",
                "verbose_name_plural": "报表收藏",
                "db_table": "t_report_favorite",
                "unique_together": {("report", "user")},
            },
        ),
    ]
