# Generated by Django 4.2.9 on 2026-01-30 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="规则名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("job_failure", "任务失败"),
                            ("job_timeout", "任务超时"),
                            ("api_error", "API错误"),
                            ("api_latency", "API延迟"),
                            ("login_failure", "登录失败"),
                            ("custom", "自定义"),
                        ],
                        max_length=50,
                        verbose_name="指标类型",
                    ),
                ),
                (
                    "condition",
                    models.JSONField(help_text="告警条件配置", verbose_name="触发条件"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("P0", "紧急"),
                            ("P1", "重要"),
                            ("P2", "一般"),
                            ("P3", "提示"),
                        ],
                        default="P2",
                        max_length=10,
                        verbose_name="告警级别",
                    ),
                ),
                (
                    "notify_channels",
                    models.JSONField(
                        default=list, help_text="邮件/钉钉/飞书等", verbose_name="通知渠道"
                    ),
                ),
                (
                    "notify_users",
                    models.JSONField(blank=True, default=list, verbose_name="通知用户"),
                ),
                (
                    "cooldown_minutes",
                    models.IntegerField(
                        default=30, help_text="告警抑制时间", verbose_name="冷却时间(分钟)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("inactive", "停用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "告警规则",
                "verbose_name_plural": "告警规则",
                "db_table": "t_alert_rule",
            },
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="用户ID"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="用户名"
                    ),
                ),
                (
                    "login_type",
                    models.CharField(
                        choices=[
                            ("password", "密码登录"),
                            ("sso", "SSO单点登录"),
                            ("mfa", "MFA验证"),
                            ("oauth", "OAuth登录"),
                        ],
                        max_length=20,
                        verbose_name="登录方式",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="登录地点"
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="设备信息"
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="浏览器"
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="操作系统"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "fail_reason",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="失败原因"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登录时间"),
                ),
            ],
            options={
                "verbose_name": "登录日志",
                "verbose_name_plural": "登录日志",
                "db_table": "t_login_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "created_at"],
                        name="t_login_log_user_id_cec108_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="t_login_log_created_29002f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=100, verbose_name="表名")),
                ("record_id", models.BigIntegerField(verbose_name="记录ID")),
                (
                    "action",
                    models.CharField(
                        choices=[("insert", "新增"), ("update", "修改"), ("delete", "删除")],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "old_data",
                    models.JSONField(blank=True, null=True, verbose_name="变更前数据"),
                ),
                (
                    "new_data",
                    models.JSONField(blank=True, null=True, verbose_name="变更后数据"),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, help_text="字段级变更详情", null=True, verbose_name="变更字段"
                    ),
                ),
                (
                    "operator_id",
                    models.BigIntegerField(blank=True, null=True, verbose_name="操作人ID"),
                ),
                (
                    "operator_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="操作人"
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=36,
                        null=True,
                        verbose_name="追踪ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
            ],
            options={
                "verbose_name": "数据变更日志",
                "verbose_name_plural": "数据变更日志",
                "db_table": "t_data_change_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["table_name", "record_id"],
                        name="t_data_chan_table_n_05c431_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="t_data_chan_created_acdb0d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="用户ID"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="用户名"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="User-Agent"
                    ),
                ),
                ("request_path", models.CharField(max_length=500, verbose_name="请求路径")),
                (
                    "request_method",
                    models.CharField(max_length=10, verbose_name="请求方法"),
                ),
                (
                    "request_body",
                    models.TextField(blank=True, null=True, verbose_name="请求体"),
                ),
                (
                    "request_params",
                    models.JSONField(blank=True, default=dict, verbose_name="请求参数"),
                ),
                (
                    "response_code",
                    models.IntegerField(blank=True, null=True, verbose_name="响应状态码"),
                ),
                (
                    "response_body",
                    models.TextField(blank=True, null=True, verbose_name="响应体"),
                ),
                (
                    "duration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="耗时(秒)",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="所属模块"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="操作类型"
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="资源类型"
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="资源ID"
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=36,
                        null=True,
                        verbose_name="追踪ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
            ],
            options={
                "verbose_name": "操作审计日志",
                "verbose_name_plural": "操作审计日志",
                "db_table": "t_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "created_at"],
                        name="t_audit_log_user_id_10e2bb_idx",
                    ),
                    models.Index(
                        fields=["request_path"], name="t_audit_log_request_2be11d_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="t_audit_log_created_4a03cb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AlertHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_name", models.CharField(max_length=100, verbose_name="规则名称")),
                ("level", models.CharField(max_length=10, verbose_name="告警级别")),
                ("title", models.CharField(max_length=200, verbose_name="告警标题")),
                ("content", models.TextField(verbose_name="告警内容")),
                (
                    "metric_value",
                    models.JSONField(blank=True, null=True, verbose_name="指标值"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("triggered", "已触发"),
                            ("acknowledged", "已确认"),
                            ("resolved", "已解决"),
                        ],
                        default="triggered",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="触发时间"),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="确认时间"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="解决时间"),
                ),
                (
                    "resolve_comment",
                    models.TextField(blank=True, null=True, verbose_name="解决说明"),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="确认人",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="解决人",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="histories",
                        to="audit.alertrule",
                        verbose_name="告警规则",
                    ),
                ),
            ],
            options={
                "verbose_name": "告警历史",
                "verbose_name_plural": "告警历史",
                "db_table": "t_alert_history",
                "ordering": ["-triggered_at"],
            },
        ),
    ]
