# Generated by Django 4.2.9 on 2026-01-30 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="任务名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="任务描述"),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("http", "HTTP请求"),
                            ("shell", "Shell脚本"),
                            ("sql", "SQL脚本"),
                            ("python", "Python脚本"),
                        ],
                        max_length=20,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "cron_expr",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Cron表达式"
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        help_text="任务配置(url/script等)", verbose_name="任务配置"
                    ),
                ),
                ("retry_count", models.IntegerField(default=3, verbose_name="重试次数")),
                (
                    "retry_interval",
                    models.IntegerField(default=60, verbose_name="重试间隔(秒)"),
                ),
                ("timeout", models.IntegerField(default=60, verbose_name="超时时间(秒)")),
                (
                    "status",
                    models.CharField(
                        choices=[("enabled", "启用"), ("disabled", "禁用")],
                        default="enabled",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "alert_on_failure",
                    models.BooleanField(default=True, verbose_name="失败告警"),
                ),
                (
                    "alert_on_timeout",
                    models.BooleanField(default=True, verbose_name="超时告警"),
                ),
                (
                    "alert_channels",
                    models.JSONField(blank=True, default=list, verbose_name="告警渠道"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
                "db_table": "t_job",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="工作流名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "dag_config",
                    models.JSONField(help_text="节点和边的配置", verbose_name="DAG配置"),
                ),
                (
                    "cron_expr",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Cron表达式"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("enabled", "启用"), ("disabled", "禁用")],
                        default="enabled",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流",
                "verbose_name_plural": "工作流",
                "db_table": "t_job_flow",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobFlowNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("node_id", models.CharField(max_length=50, verbose_name="节点ID")),
                ("position_x", models.IntegerField(default=0, verbose_name="X坐标")),
                ("position_y", models.IntegerField(default=0, verbose_name="Y坐标")),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="节点配置"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="scheduler.jobflow",
                        verbose_name="所属工作流",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_nodes",
                        to="scheduler.job",
                        verbose_name="关联任务",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流节点",
                "verbose_name_plural": "工作流节点",
                "db_table": "t_job_flow_node",
            },
        ),
        migrations.CreateModel(
            name="HistoricalJobFlow",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="更新时间"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="工作流名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "dag_config",
                    models.JSONField(help_text="节点和边的配置", verbose_name="DAG配置"),
                ),
                (
                    "cron_expr",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Cron表达式"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("enabled", "启用"), ("disabled", "禁用")],
                        default="enabled",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 工作流",
                "verbose_name_plural": "historical 工作流",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalJob",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="更新时间"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="任务名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="任务描述"),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("http", "HTTP请求"),
                            ("shell", "Shell脚本"),
                            ("sql", "SQL脚本"),
                            ("python", "Python脚本"),
                        ],
                        max_length=20,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "cron_expr",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Cron表达式"
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        help_text="任务配置(url/script等)", verbose_name="任务配置"
                    ),
                ),
                ("retry_count", models.IntegerField(default=3, verbose_name="重试次数")),
                (
                    "retry_interval",
                    models.IntegerField(default=60, verbose_name="重试间隔(秒)"),
                ),
                ("timeout", models.IntegerField(default=60, verbose_name="超时时间(秒)")),
                (
                    "status",
                    models.CharField(
                        choices=[("enabled", "启用"), ("disabled", "禁用")],
                        default="enabled",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "alert_on_failure",
                    models.BooleanField(default=True, verbose_name="失败告警"),
                ),
                (
                    "alert_on_timeout",
                    models.BooleanField(default=True, verbose_name="超时告警"),
                ),
                (
                    "alert_channels",
                    models.JSONField(blank=True, default=list, verbose_name="告警渠道"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 任务",
                "verbose_name_plural": "historical 任务",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="JobLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flow_instance_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="工作流实例ID"
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(db_index=True, max_length=36, verbose_name="追踪ID"),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("cron", "定时触发"),
                            ("manual", "手动触发"),
                            ("flow", "工作流触发"),
                            ("retry", "重试触发"),
                        ],
                        default="cron",
                        max_length=20,
                        verbose_name="触发类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("timeout", "超时"),
                            ("cancelled", "已取消"),
                            ("skipped", "已跳过"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "duration",
                    models.IntegerField(blank=True, null=True, verbose_name="耗时(毫秒)"),
                ),
                (
                    "input_params",
                    models.JSONField(blank=True, default=dict, verbose_name="输入参数"),
                ),
                (
                    "result",
                    models.TextField(blank=True, null=True, verbose_name="执行结果"),
                ),
                (
                    "error_msg",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                ("retry_count", models.IntegerField(default=0, verbose_name="重试次数")),
                (
                    "flow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="scheduler.jobflow",
                        verbose_name="所属工作流",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="scheduler.job",
                        verbose_name="任务",
                    ),
                ),
                (
                    "trigger_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="触发人",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务执行日志",
                "verbose_name_plural": "任务执行日志",
                "db_table": "t_job_log",
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["job", "start_time"], name="t_job_log_job_id_a64b10_idx"
                    ),
                    models.Index(
                        fields=["trace_id"], name="t_job_log_trace_i_e36757_idx"
                    ),
                ],
            },
        ),
    ]
