# Generated by Django 4.2.9 on 2026-01-30 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_id",
                    models.CharField(max_length=50, unique=True, verbose_name="实例ID"),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("cron", "定时触发"),
                            ("manual", "手动触发"),
                            ("api", "API触发"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="触发类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("partial", "部分成功"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "duration",
                    models.IntegerField(blank=True, null=True, verbose_name="耗时(毫秒)"),
                ),
                (
                    "input_params",
                    models.JSONField(blank=True, default=dict, verbose_name="输入参数"),
                ),
                (
                    "result",
                    models.JSONField(blank=True, default=dict, verbose_name="执行结果"),
                ),
                (
                    "error_msg",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
            ],
            options={
                "verbose_name": "工作流实例",
                "verbose_name_plural": "工作流实例",
                "db_table": "t_flow_instance",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="JobAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("failure", "执行失败"),
                            ("timeout", "执行超时"),
                            ("threshold", "阈值告警"),
                        ],
                        max_length=20,
                        verbose_name="告警类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="告警标题")),
                ("content", models.TextField(verbose_name="告警内容")),
                ("channels", models.JSONField(default=list, verbose_name="发送渠道")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("sent", "已发送"),
                            ("acknowledged", "已确认"),
                            ("resolved", "已解决"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发送时间"),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="确认时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "任务告警",
                "verbose_name_plural": "任务告警",
                "db_table": "t_job_alert",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="joblog",
            name="flow_instance_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                verbose_name="工作流实例ID",
            ),
        ),
        migrations.AddIndex(
            model_name="joblog",
            index=models.Index(
                fields=["flow_instance_id"], name="t_job_log_flow_in_af88dd_idx"
            ),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_job_alerts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="确认人",
            ),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="scheduler.job",
                verbose_name="任务",
            ),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="scheduler.joblog",
                verbose_name="执行日志",
            ),
        ),
        migrations.AddField(
            model_name="flowinstance",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="scheduler.jobflow",
                verbose_name="工作流",
            ),
        ),
        migrations.AddField(
            model_name="flowinstance",
            name="trigger_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_flows",
                to=settings.AUTH_USER_MODEL,
                verbose_name="触发人",
            ),
        ),
        migrations.AddIndex(
            model_name="flowinstance",
            index=models.Index(
                fields=["flow", "start_time"], name="t_flow_inst_flow_id_cf3a6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowinstance",
            index=models.Index(
                fields=["instance_id"], name="t_flow_inst_instanc_39ae40_idx"
            ),
        ),
    ]
