# Generated by Django 4.2.9 on 2026-01-30 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="流程名称")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="流程编码"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "nodes",
                    models.JSONField(help_text="流程节点JSON配置", verbose_name="节点配置"),
                ),
                ("edges", models.JSONField(help_text="节点连接关系", verbose_name="边配置")),
                (
                    "form_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="审批表单字段配置",
                        verbose_name="表单配置",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="版本号")),
                (
                    "trigger_business_types",
                    models.JSONField(blank=True, default=list, verbose_name="关联业务类型"),
                ),
                (
                    "callback_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="审批通过/拒绝后的回调",
                        verbose_name="回调配置",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "流程定义",
                "verbose_name_plural": "流程定义",
                "db_table": "t_workflow_definition",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalWorkflowDefinition",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="更新时间"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="流程名称")),
                (
                    "code",
                    models.CharField(db_index=True, max_length=50, verbose_name="流程编码"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "nodes",
                    models.JSONField(help_text="流程节点JSON配置", verbose_name="节点配置"),
                ),
                ("edges", models.JSONField(help_text="节点连接关系", verbose_name="边配置")),
                (
                    "form_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="审批表单字段配置",
                        verbose_name="表单配置",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="版本号")),
                (
                    "trigger_business_types",
                    models.JSONField(blank=True, default=list, verbose_name="关联业务类型"),
                ),
                (
                    "callback_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="审批通过/拒绝后的回调",
                        verbose_name="回调配置",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 流程定义",
                "verbose_name_plural": "historical 流程定义",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ApprovalInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="审批标题")),
                (
                    "business_type",
                    models.CharField(
                        help_text="关联的业务模块", max_length=50, verbose_name="业务类型"
                    ),
                ),
                (
                    "business_id",
                    models.BigIntegerField(help_text="关联的业务记录ID", verbose_name="业务ID"),
                ),
                (
                    "form_data",
                    models.JSONField(blank=True, default=dict, verbose_name="表单数据"),
                ),
                (
                    "current_node",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="当前节点"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "审批中"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("cancelled", "已取消"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="提交时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("normal", "普通"),
                            ("urgent", "紧急"),
                            ("very_urgent", "非常紧急"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="紧急程度",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="workflow.workflowdefinition",
                        verbose_name="流程定义",
                    ),
                ),
            ],
            options={
                "verbose_name": "审批实例",
                "verbose_name_plural": "审批实例",
                "db_table": "t_approval_instance",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalCc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="抄送节点"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="是否已读")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="阅读时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="抄送时间"),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ccs",
                        to="workflow.approvalinstance",
                        verbose_name="审批实例",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cc_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="抄送人",
                    ),
                ),
            ],
            options={
                "verbose_name": "审批抄送",
                "verbose_name_plural": "审批抄送",
                "db_table": "t_approval_cc",
            },
        ),
        migrations.CreateModel(
            name="ApprovalTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=50, verbose_name="节点ID")),
                (
                    "node_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="节点名称"
                    ),
                ),
                (
                    "assign_type",
                    models.CharField(
                        choices=[
                            ("user", "指定用户"),
                            ("role", "指定角色"),
                            ("department", "部门主管"),
                            ("applicant_select", "申请人自选"),
                        ],
                        default="user",
                        max_length=20,
                        verbose_name="分配方式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("completed", "已完成"),
                            ("transferred", "已转交"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "due_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="截止时间"),
                ),
                ("reminded_count", models.IntegerField(default=0, verbose_name="催办次数")),
                (
                    "last_reminded_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后催办时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="workflow.approvalinstance",
                        verbose_name="审批实例",
                    ),
                ),
            ],
            options={
                "verbose_name": "审批任务",
                "verbose_name_plural": "审批任务",
                "db_table": "t_approval_task",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["assignee", "status"],
                        name="t_approval__assigne_8dc74f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=50, verbose_name="节点ID")),
                (
                    "node_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="节点名称"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "提交"),
                            ("approve", "同意"),
                            ("reject", "拒绝"),
                            ("transfer", "转交"),
                            ("add_approver", "加签"),
                            ("withdraw", "撤回"),
                            ("urge", "催办"),
                            ("comment", "评论"),
                        ],
                        max_length=20,
                        verbose_name="操作",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="审批意见"),
                ),
                (
                    "attachments",
                    models.JSONField(blank=True, default=list, verbose_name="附件列表"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="workflow.approvalinstance",
                        verbose_name="审批实例",
                    ),
                ),
                (
                    "transfer_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferred_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="转交给",
                    ),
                ),
            ],
            options={
                "verbose_name": "审批记录",
                "verbose_name_plural": "审批记录",
                "db_table": "t_approval_record",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["instance"], name="t_approval__instanc_d9c996_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="approvalinstance",
            index=models.Index(
                fields=["business_type", "business_id"],
                name="t_approval__busines_d92eee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalinstance",
            index=models.Index(
                fields=["applicant", "status"], name="t_approval__applica_437afc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="approvalcc",
            unique_together={("instance", "user")},
        ),
    ]
