# Generated by Django 4.2.9 on 2026-01-30 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("email", "邮箱"), ("phone", "手机号"), ("user", "用户")],
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="邮箱/手机号/用户ID", max_length=200, verbose_name="值"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("unsubscribe", "用户退订"),
                            ("bounce", "邮件退信"),
                            ("complaint", "用户投诉"),
                            ("manual", "手动添加"),
                        ],
                        max_length=20,
                        verbose_name="原因",
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "通知黑名单",
                "verbose_name_plural": "通知黑名单",
                "db_table": "t_notification_blacklist",
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("code", models.CharField(max_length=50, verbose_name="模板编码")),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "邮件"),
                            ("sms", "短信"),
                            ("dingtalk", "钉钉"),
                            ("feishu", "飞书"),
                            ("wechat", "企业微信"),
                            ("webhook", "Webhook"),
                            ("internal", "站内信"),
                        ],
                        max_length=20,
                        verbose_name="渠道",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="邮件主题等",
                        max_length=200,
                        null=True,
                        verbose_name="主题/标题",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="支持变量如 ${userName}, ${taskName}", verbose_name="模板内容"
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="模板支持的参数列表",
                        verbose_name="参数说明",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("disabled", "禁用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息模板",
                "verbose_name_plural": "消息模板",
                "db_table": "t_message_template",
                "unique_together": {("code", "channel")},
            },
        ),
        migrations.CreateModel(
            name="ChannelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "邮件"),
                            ("sms", "短信"),
                            ("dingtalk", "钉钉"),
                            ("feishu", "飞书"),
                            ("wechat", "企业微信"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="渠道",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="渠道名称")),
                (
                    "config",
                    models.JSONField(help_text="API密钥、服务器配置等", verbose_name="配置信息"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("disabled", "禁用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "last_test_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后测试时间"),
                ),
                (
                    "last_test_result",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="最后测试结果"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "渠道配置",
                "verbose_name_plural": "渠道配置",
                "db_table": "t_channel_config",
            },
        ),
        migrations.CreateModel(
            name="UserNotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        help_text="如 approval, task, alert",
                        max_length=50,
                        verbose_name="通知类型",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, verbose_name="邮件通知"),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(default=False, verbose_name="短信通知"),
                ),
                ("im_enabled", models.BooleanField(default=True, verbose_name="IM通知")),
                (
                    "internal_enabled",
                    models.BooleanField(default=True, verbose_name="站内信通知"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户通知设置",
                "verbose_name_plural": "用户通知设置",
                "db_table": "t_user_notification_setting",
                "unique_together": {("user", "notification_type")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(blank=True, null=True, verbose_name="内容")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("system", "系统公告"),
                            ("approval", "审批通知"),
                            ("task", "任务通知"),
                            ("alert", "告警通知"),
                            ("personal", "个人消息"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "普通"),
                            ("warning", "警告"),
                            ("error", "错误"),
                            ("success", "成功"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="级别",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="是否已读")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="阅读时间"),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="链接地址"
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="业务类型"
                    ),
                ),
                (
                    "business_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="业务ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "站内通知",
                "verbose_name_plural": "站内通知",
                "db_table": "t_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="t_notificat_user_id_41e2e6_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(max_length=20, verbose_name="渠道")),
                (
                    "recipient",
                    models.CharField(
                        help_text="邮箱/手机号/用户ID等", max_length=200, verbose_name="接收人"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="接收人名称"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="主题"
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "params",
                    models.JSONField(blank=True, default=dict, verbose_name="模板参数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待发送"),
                            ("sent", "已发送"),
                            ("failed", "发送失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("retry_count", models.IntegerField(default=0, verbose_name="重试次数")),
                ("max_retry", models.IntegerField(default=3, verbose_name="最大重试次数")),
                (
                    "error_msg",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="错误信息"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="第三方平台返回的消息ID",
                        max_length=100,
                        null=True,
                        verbose_name="外部ID",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发送时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "business_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="业务类型"
                    ),
                ),
                (
                    "business_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="业务ID"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="notification.messagetemplate",
                        verbose_name="消息模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息发送记录",
                "verbose_name_plural": "消息发送记录",
                "db_table": "t_message_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="t_message_l_status_7c24cb_idx",
                    ),
                    models.Index(
                        fields=["channel", "created_at"],
                        name="t_message_l_channel_1cc1dc_idx",
                    ),
                ],
            },
        ),
    ]
