# Generated by Django 4.2.9 on 2026-01-30 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="配置键"),
                ),
                ("value", models.JSONField(verbose_name="配置值")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("system", "系统配置"),
                            ("security", "安全配置"),
                            ("email", "邮件配置"),
                            ("sms", "短信配置"),
                            ("storage", "存储配置"),
                            ("other", "其他"),
                        ],
                        default="system",
                        max_length=50,
                        verbose_name="分类",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "is_encrypted",
                    models.BooleanField(default=False, verbose_name="是否加密"),
                ),
                (
                    "is_readonly",
                    models.BooleanField(default=False, verbose_name="是否只读"),
                ),
                (
                    "effective_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="生效时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "db_table": "t_system_config",
            },
        ),
        migrations.CreateModel(
            name="MetaTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="表名"),
                ),
                ("display_name", models.CharField(max_length=100, verbose_name="显示名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "field_config",
                    models.JSONField(help_text="字段定义JSON配置", verbose_name="字段配置"),
                ),
                (
                    "need_audit",
                    models.BooleanField(
                        default=False, help_text="修改是否需要审批", verbose_name="需要审批"
                    ),
                ),
                (
                    "need_history",
                    models.BooleanField(
                        default=True, help_text="是否记录变更历史", verbose_name="记录历史"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("inactive", "停用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "read_roles",
                    models.JSONField(blank=True, default=list, verbose_name="可读角色"),
                ),
                (
                    "write_roles",
                    models.JSONField(blank=True, default=list, verbose_name="可写角色"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "元数据表",
                "verbose_name_plural": "元数据表",
                "db_table": "t_meta_table",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalSystemConfig",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="更新时间"
                    ),
                ),
                (
                    "key",
                    models.CharField(db_index=True, max_length=100, verbose_name="配置键"),
                ),
                ("value", models.JSONField(verbose_name="配置值")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("system", "系统配置"),
                            ("security", "安全配置"),
                            ("email", "邮件配置"),
                            ("sms", "短信配置"),
                            ("storage", "存储配置"),
                            ("other", "其他"),
                        ],
                        default="system",
                        max_length=50,
                        verbose_name="分类",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "is_encrypted",
                    models.BooleanField(default=False, verbose_name="是否加密"),
                ),
                (
                    "is_readonly",
                    models.BooleanField(default=False, verbose_name="是否只读"),
                ),
                (
                    "effective_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="生效时间"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 系统配置",
                "verbose_name_plural": "historical 系统配置",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMetaTable",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="更新时间"
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=100, verbose_name="表名"),
                ),
                ("display_name", models.CharField(max_length=100, verbose_name="显示名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "field_config",
                    models.JSONField(help_text="字段定义JSON配置", verbose_name="字段配置"),
                ),
                (
                    "need_audit",
                    models.BooleanField(
                        default=False, help_text="修改是否需要审批", verbose_name="需要审批"
                    ),
                ),
                (
                    "need_history",
                    models.BooleanField(
                        default=True, help_text="是否记录变更历史", verbose_name="记录历史"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("inactive", "停用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "read_roles",
                    models.JSONField(blank=True, default=list, verbose_name="可读角色"),
                ),
                (
                    "write_roles",
                    models.JSONField(blank=True, default=list, verbose_name="可写角色"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical 元数据表",
                "verbose_name_plural": "historical 元数据表",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ConfigApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("table_name", models.CharField(max_length=100, verbose_name="表名")),
                (
                    "record_id",
                    models.BigIntegerField(
                        blank=True, help_text="新增时为空", null=True, verbose_name="记录ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("insert", "新增"), ("update", "修改"), ("delete", "删除")],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "old_data",
                    models.JSONField(blank=True, null=True, verbose_name="变更前数据"),
                ),
                ("new_data", models.JSONField(verbose_name="变更后数据")),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="申请备注"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审批时间"),
                ),
                (
                    "approve_remark",
                    models.TextField(blank=True, null=True, verbose_name="审批备注"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "配置审批",
                "verbose_name_plural": "配置审批",
                "db_table": "t_config_approval",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConfigHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=100, verbose_name="表名")),
                ("record_id", models.BigIntegerField(verbose_name="记录ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("insert", "新增"),
                            ("update", "修改"),
                            ("delete", "删除"),
                            ("rollback", "回滚"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("version", models.IntegerField(verbose_name="版本号")),
                (
                    "old_data",
                    models.JSONField(blank=True, null=True, verbose_name="变更前数据"),
                ),
                (
                    "new_data",
                    models.JSONField(blank=True, null=True, verbose_name="变更后数据"),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, help_text="字段级变更详情", null=True, verbose_name="变更字段"
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, help_text="修改原因", null=True, verbose_name="备注"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "配置历史",
                "verbose_name_plural": "配置历史",
                "db_table": "t_config_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["table_name", "record_id"],
                        name="t_config_hi_table_n_e7c09b_idx",
                    )
                ],
            },
        ),
    ]
